Use .cozmars directory
hyansuper/rcute-cozmars-server pull request #15
Opened 2020-12-07 05:58 UTC by anjok

- should use a directory instead of a bunch of files
- fix typo in README.md
- remove comment from conf.json

2020-12-07 12:01 UTC, anjok commented
Actually, please don't pull this yet. I can't use different branches for the different issues as I don't know your schedule and they almost all overlap.

So what I did here:

- added gettext + locale
- moved all .tmpl to .html, as they are easier to view in the finder preview
- fixed all Chinese text to google-translated gettext messages

The next step is to generate the locales/base.dot file and add the various translations.

Please don't pull this yet, as I can't test any of this due of a lack of a configured raspi. I still need some parts.

But if possible, don't create conflicts for me yet...

2020-12-07 12:04 UTC, anjok commented
Unfortunately you would need to regenerate the Chinese text from the to-be-created gettext files. Since I have no idea what the characters are, I would just create a mess and it would take ages.

2020-12-08 00:04 UTC, anjok commented
@hyansuper  ok, localisation seems to work now. It would be great if you could take a look.

2020-12-09 14:42 UTC, hyansuper commented
thank you for the effort, I am looking at it.
I have not used gettext before, may take a while

2020-12-10 09:07 UTC, anjok commented
Please re-fetch the PR, I squashed the commits and rebased on your latest code.

Note that it's *very* hard for me to merge incoming changes of yours into my branch as I have no idea what your code actually spells... so please decide soon if you want to do the localisation or not. If not, I have to keep my own fork and won't be able to contribute.

I was working with this here:

https://phrase.com/blog/posts/translate-python-gnu-gettext/

it's basically:

`
cd rcute_cozmars_server
(wherever this is)/pygettext.py -d base -o locales/base.pot *.py *.html
`

Then generate loc files for each non-english language and fill in the blanks. It's really easy to use.

You'd need to proofread the English (as they are the keys, they need to be pretty good) and fill in the generated Chinese.

2020-12-10 11:56 UTC, hyansuper requested changes
just a few

2020-12-10 11:56 UTC, hyansuper commented on rcute_cozmars_server/static/servo.html
> -<h2>头部&nbsp;&nbsp;&nbsp;&nbsp;<span id='head_val'>0°</span></h2>
did you missd line 55~56, they are for head servo calibration

2020-12-10 11:56 UTC, hyansuper commented on rcute_cozmars_server/util.py
> +    with open(util.static("{}.html".format(name))) as file:
"util.static" -> just "static"

2020-12-10 11:56 UTC, hyansuper commented on rcute_cozmars_server/util.py
> +
import re

2020-12-10 11:56 UTC, hyansuper commented on rcute_cozmars_server/static/test.html
> +<h3>{_("Motor test")}  <input id='sec' type='number' size='1' value='2'/>{_("Speed")}</h3>
"Speed" -> "second"

2020-12-10 11:56 UTC, hyansuper commented on requirements.txt
> +gettext
no need to require gettext and locale, they are builtin with python3, they can't be installed individually

2020-12-10 11:56 UTC, hyansuper commented on rcute_cozmars_server/__main__.py
> +import re
move this line to file util.py

2020-12-10 11:56 UTC, hyansuper commented on rcute_cozmars_server/static/index.html
> +		<a href='servo'> <button{_("Servo calibration")}</button></a><a href='motor'><button>{_("Motor calibration")}</button></a>
"<button" -> left a ">" sign

2020-12-10 11:56 UTC, hyansuper commented on rcute_cozmars_server/static/motor.html
> +		return fetch('http://'+location.host+'/config').then(j=>j.json()).then(c=>{{
config -> conf

2020-12-10 11:56 UTC, hyansuper commented on rcute_cozmars_server/static/servo.html
> +		return fetch('http://'+location.host+'/config').then(j=>j.json()).then(c=>{{
config -> conf

2020-12-10 11:56 UTC, hyansuper commented on rcute_cozmars_server/static/test.html
> +<script src="https://cdn.jsdelivr.net/gh/hyansuper/rcute-cozmars-server/server/static/cozmars.min.js"></script>
this line should not change

2020-12-10 11:56 UTC, hyansuper commented on rcute_cozmars_server/static/test.html
> +<h3>{_("Motor test")}  <input id='sec' type='number' size='1' value='2'/>{_("Speed")}</h3>
_("Speed") => _("seconds")

2020-12-10 11:56 UTC, hyansuper commented on rcute_cozmars_server/util.py
> +
import re

2020-12-10 11:56 UTC, hyansuper commented on requirements.txt
> +gettext
gettext and locale is builtin with python3. don't need to require gettext and locale, they can't be installed individually

2020-12-10 12:00 UTC, hyansuper commented
sorry I made some duplicated change requests

2020-12-10 13:29 UTC, anjok commented
ok, will fix and push later

2020-12-10 14:19 UTC, anjok commented
@hyansuper please review again.

2020-12-10 14:24 UTC, anjok commented
also, see:

https://stackoverflow.com/questions/27214065/how-to-docstring-in-python-for-multiple-languages

for the doctoring comments.

2020-12-10 14:26 UTC, hyansuper approved these changes

2020-12-10 14:27 UTC, merged

2020-12-12 13:09 UTC, hyansuper commented
@anjok  did you have to hack pygettext.py in order to handle .html? 
I think this command also works `pygettext -d base -o locales/base.pot *.py static/*.html `
but a few english aren't extracted in html, especially those in javascript, maybe it has to do with "quote in quote in quoat...". I have to manually type into .pot file

2020-12-12 13:23 UTC, anjok commented
Oh ok. I didn't verify it got everything. Worst case one need to put the error strings in a server side duct